export const Routes = {
    homePage: '/',
    pageNotFound: '/pagina-no-encontrada',
    detailCategory: '/categoria/:id',
    nosotros: '/nosotros',
    contacto: '/contacto',
    carrito: '/carrito',
    admin: '/admin',
    adminHome: '/admin/home',
    adminSalesReport: '/admin/sales-report',
    adminCustomerManagement: '/admin/customer-management',
    adminOrdersManagement: '/admin/orders-management',
    adminSystemManagement: '/admin/system-management',
    adminPageManagement: '/admin/page-management',
}